version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '33306:3306'
  php:
    build: ./php
    ports:
      - '8088:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
